config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #CRUD
  #READ
  resources :restaurants
  # get "/restaurants", to: "restaurants#index", as: "restaurants"
  # get "/restaurants/:id", to: "restaurants#show", as: "restaurant"

  # #CREATE
  # get "/restaurants/new", to: "restaurants#new", as: "new_restaurant"
  # post "/restaurants", to: "restaurants#create"
  # #UPDATE
  # get "/restaurants/:id/edit", to: "restaurants#edit", as: "edit_restaurant"
  # patch "/restaurants/:id", to: "restaurants#update"
  # #DELETE
  # delete "/restaurants/:id", to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :stars, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    return params.require(:restaurant).permit(:name, :address, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thespoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :stars %>
  <%= f.text_field :stars %>
  <%= f.button %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<%= render "form" %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.address %></p>
  <p><%= "$" * restaurant.stars %></p>
  <%= link_to "See the restaurant", restaurant_path(restaurant.id)%>
  <%= link_to "Destroy", restaurant_path(restaurant.id), data: { confirm: "Are you sure?" }, method: :delete %>
  <hr>
<% end %>

<%= link_to "add a restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Create Restaurant</h1>

<%= render "form" %>


<%# <form action="/restaurants" method="post">
  <%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%# <label for="name">Name</label>
  <input type="text" name="restaurant[name]">
  <label for="name">Address</label>
  <input type="text" name="restaurant[address]">
  <label for="name">Stars</label>
  <input type="text" name="restaurant[stars]">
  <input type="submit" value="create">
</form> %> 

app/views/restaurants/show.html.erb
  <h1>Show Page</h1>
  
  <h2><%= @restaurant.name %></h2>
  <p><%= @restaurant.address %></p>
  <p><%= "$" * @restaurant.stars %></p>

<%= link_to "Go back", restaurants_path %>
<%= link_to "Edit", edit_restaurant_path(@restaurant.id) %>